[theme]
base = "light"
primaryColor = "#24507C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F4F8"
textColor = "#16273A"
borderColor = "#DCE3EC"
linkColor = "#24507C"
font = "sans serif"
baseRadius = "medium"
buttonRadius = "medium"
showWidgetBorder = true
showSidebarBorder = true

[browser]
gatherUsageStats = false
